# ----------------------------------------------------------------------------------------------------
# Pipeline to build and deploy one Container App Module
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'
# ----------------------------------------------------------------------------------------------------
trigger: none

# ----------------------------------------------------------------------------------------------------
parameters:
- name: buildApps
  displayName: Build Docker Images
  type: boolean
  default: true
- name: pushApps
  displayName: Push Images to ACR
  type: boolean
  default: true
- name: deployAction
  displayName: Deploy Action
  type: string
  values:
    - build-deploy
    - create-build-deploy
    - none
- name: runMSDevSecOpsScan
  displayName: Run Scan
  type: boolean
  default: false

- name: updateACRFirewall
  displayName: Update ACR Firewall
  type: boolean 
  default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.LZ.Secrets
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if parameters.runMSDevSecOpsScan }}:
    - stage: ScanApplication
      displayName: Scan Application
      jobs:
        - template: pipes/templates/scan-code-template.yml
          parameters:
            environmentName: 'DEV'
            runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
            runGHASScan: false

- template: pipes/build-deploy-app-pipe.yml
  parameters:
    pushToACR: ${{ parameters.pushApps }}
    deployAction: ${{ parameters.deployAction }}
    updateACRFirewall: ${{ parameters.updateACRFirewall }}
    apps: [ 
      { containerAppName: 'ui',  acrAppName: 'chatui',  projectFolderName: 'src/website/chatui', port: '8080' }
    ] 
