# ----------------------------------------------------------------------------------------------------
# Pipe to build an Azure Container App for multiple apps and environments
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environments
    type: object
    default: ['DEV']
  - name: singleEnvironment
    default: 'false'
  - name: apps
    type: object
    default: []
  - name: pushToACR
    default: true
    type: boolean
  - name: deployAction
    default: 'build-deploy'  # Options: 'build-deploy', 'create-build-deploy', 'none'
  - name: updateACRFirewall
    default: false
  - name: runGHASScan
    default: 'false'
  - name: runMSDevSecOpsScan
    default: 'false'

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if or(eq(lower(parameters.runMSDevSecOpsScan), 'true'), eq(lower(parameters.runGHASScan), 'true')) }}:
    - stage: ScanApplication
      displayName: Scan Application
      jobs:
        - template: templates/scan-code-template.yml
          parameters:
            environmentCode: ${{ parameters.environments[0] }}
            runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
            runGHASScan: ${{ parameters.runGHASScan }}

# ----------------------------------------------------------------------------------------------------
- ${{ each environmentCode in parameters.environments }}:
  - ${{ each app in parameters.apps }}:
    # -- BUILD STAGE - Based on environment ----------------------------------------------------------
    - stage: Build${{ app.containerAppName }}${{ environmentCode }}
      displayName: Build ${{ app.containerAppName }} ${{ environmentCode }}
      condition: or(eq(${{ parameters.singleEnvironment }}, 'true'), eq(upper('${{ environmentCode }}'), 'DEV'), and(eq(upper('${{ environmentCode }}'), 'QA'), succeeded('Deploy${{ app.containerAppName }}Dev')), and(eq(upper('${{ environmentCode }}'), 'PROD'), succeeded('Deploy${{ app.containerAppName }}QA')))
      jobs:
        - ${{ if eq(upper(environmentCode), 'DEV') }}:
          - template: templates/aca-build-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionDEV)
              environmentCode: ${{ environmentCode }}
              acrAppName: ${{ app.acrAppName }}
              projectFolderName: ${{ app.projectFolderName }}
              pushToACR: ${{ parameters.pushToACR }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'QA') }}:
          - template: templates/aca-build-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionQA)
              environmentCode: ${{ environmentCode }}
              acrAppName: ${{ app.acrAppName }}
              projectFolderName: ${{ app.projectFolderName }}
              pushToACR: ${{ parameters.pushToACR }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'PROD') }}:
          - template: templates/aca-build-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionPROD)
              environmentCode: ${{ environmentCode }}
              acrAppName: ${{ app.acrAppName }}
              projectFolderName: ${{ app.projectFolderName }}
              pushToACR: ${{ parameters.pushToACR }}
              updateFirewall: ${{ parameters.updateACRFirewall }}

    # -- DEPLOY STAGE - Based on environment ----------------------------------------------------------
    - stage: Deploy${{ app.containerAppName }}${{ environmentCode }}
      displayName: Deploy ${{ app.containerAppName }} ${{ environmentCode }}
      condition: and(succeeded(), eq(lower('${{ parameters.deployAction }}'), 'build-deploy'))
      dependsOn: Build${{ app.containerAppName }}${{ environmentCode }}
      jobs:
        - ${{ if eq(upper(environmentCode), 'DEV') }}:
          - template: templates/aca-deploy-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionDEV)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'QA') }}:
          - template: templates/aca-deploy-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionQA)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'PROD') }}:
          - template: templates/aca-deploy-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionPROD)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
  
    # -- CREATE STAGE - Based on environment ----------------------------------------------------------
    - stage: Create${{ app.containerAppName }}${{ environmentCode }}
      displayName: Create ${{ app.containerAppName }} ${{ environmentCode }}
      condition: and(succeeded(), eq(lower('${{ parameters.deployAction }}'), 'create-build-deploy'))
      dependsOn: Build${{ app.containerAppName }}${{ environmentCode }}
      jobs:
        - ${{ if eq(upper(environmentCode), 'DEV') }}:
          - template: templates/aca-create-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionDEV)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'QA') }}:
          - template: templates/aca-create-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionQA)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
        - ${{ if eq(upper(environmentCode), 'PROD') }}:
          - template: templates/aca-create-template.yml
            parameters:
              serviceConnectionName: $(serviceConnectionPROD)
              environmentCode: ${{ environmentCode }}
              containerAppName: ${{ app.containerAppName }}
              acrAppName: ${{ app.acrAppName }}
              port: ${{ app.port }}
              updateFirewall: ${{ parameters.updateACRFirewall }}
