# ----------------------------------------------------------------------------------------------------
# Pipe to build an Azure Container App for multiple apps and environments
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environments
    type: object
    default: ['DEV']
  - name: apps
    type: object
    default: []
  - name: pushToACR
    default: true
    type: boolean

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ each environmentCode in parameters.environments }}:
  - ${{ each app in parameters.apps }}:
    - stage: Build${{ app.containerAppName }}${{ environmentCode }}Service
      displayName: Build ${{ app.containerAppName }} ${{ environmentCode }}
      jobs:
        - template: templates/aca-build-template.yml
          parameters:
            serviceConnectionName: $(serviceConnectionName)
            acrAppName: ${{ app.acrAppName }}
            projectFolderName: ${{ app.projectFolderName }}
            environmentCode: ${{ environmentCode }}
            pushToACR: ${{ parameters.pushToACR }}
