# ----------------------------------------------------------------------------------------------------
# Pipe to build an Azure Container App for multiple apps and environments
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environmentCode
    type: string
    default: 'DEV'

  - name: pushToACR
    default: true
    type: boolean

  - name: deployAPI
    default: true
    type: boolean
  - name: apiConfig
    type: object
    default: {}

  - name: deployUI
    default: false
    type: boolean
  - name: uiConfig
    type: object
    default: {}

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildAll${{ parameters.environmentcode }}Service
  displayName: Build All ${{ parameters.environmentcode }}
  jobs:
    - template: templates/aca-build-all-template.yml
      parameters:
        serviceConnectionName: $(serviceConnectionName)
        environmentCode: ${{ parameters.environmentcode }}
        pushToACR: ${{ parameters.pushToACR }}

        apiAcrAppName: ${{ parameters.apiConfig.acrAppName }}
        apiProjectFolderName: ${{ parameters.apiConfig.projectFolderName }}

        uiAcrAppName: ${{ parameters.uiConfig.acrAppName }}
        uiProjectFolderName: ${{ parameters.uiConfig.projectFolderName }}
